server:
  port: ${PORT:8080}
spring:
  application.name: ${APP_NAME:backend}
  main.banner-mode: "off"
logging:
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info
    org.springframework: info
    com.danielkreitsch: ${LOG_LEVEL:info}
